# Generated by Django 6.0.2 on 2026-02-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("Baja", "Baja"), ("Media", "Media"), ("Alta", "Alta")],
                default="Media",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("En Progreso", "En Progreso"),
                    ("Completado", "Completado"),
                ],
                default="Pendiente",
                max_length=15,
            ),
        ),
    ]
