# Generated by Django 6.0.2 on 2026-02-26 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_priority_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
