# Generated by Django 6.0.2 on 2026-02-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_task_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("Work", "Work"),
                    ("Home", "Home"),
                    ("Urgent", "Urgent"),
                ],
                default="General",
                max_length=20,
            ),
        ),
    ]
